services:
  - type: web
    name: matilda-kitchen
    runtime: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PUBLIC_URL
        sync: false
      - key: MERCADOPAGO_ACCESS_TOKEN
        sync: false
      - key: MERCADOPAGO_TEST_MODE
        value: "true"
